# Generated by Django 4.2.7 on 2024-10-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('librarian', 'librarian')], default='customer'),
        ),
    ]
