# Generated by Django 4.2.7 on 2024-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers_user_llast_name_user_phone_and_more'),
    ]

    operations = [
     
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
